version: "3.8"
services:
  frontend:
    build: ./client
    container_name: examium-frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
  backend:
    build: ./server
    container_name: examium-backend
    ports:
      - "3000:3000"
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: your-root-password
      MYSQL_DATABASE: your-database-name
      MYSQL_USER: your-username
      MYSQL_PASSWORD: your-password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:  # Define a named volume for MySQL data persistence
